package Ventanas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class Vent_Main extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public Vent_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_Unidad_1 = new javax.swing.JButton();
        Btn_Unidad_2 = new javax.swing.JButton();
        Btn_Unidad_3 = new javax.swing.JButton();
        Btn_Integrantes = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Chemestry App");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 20));

        Btn_Unidad_1.setText("Unidad 1");
        Btn_Unidad_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Unidad_1MouseClicked(evt);
            }
        });
        Btn_Unidad_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Unidad_1ActionPerformed(evt);
            }
        });

        Btn_Unidad_2.setText("Unidad 2");
        Btn_Unidad_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Unidad_2MouseClicked(evt);
            }
        });

        Btn_Unidad_3.setText("Unidad 3");
        Btn_Unidad_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Unidad_3MouseClicked(evt);
            }
        });
        Btn_Unidad_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Unidad_3ActionPerformed(evt);
            }
        });

        Btn_Integrantes.setText("Integrantes");
        Btn_Integrantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_IntegrantesMouseClicked(evt);
            }
        });
        Btn_Integrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IntegrantesActionPerformed(evt);
            }
        });

        Btn_Salir.setText("Salir");
        Btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_SalirMouseClicked(evt);
            }
        });

        jLabel2.setText("¿Que formulas quieres?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Btn_Salir)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Integrantes)
                            .addComponent(Btn_Unidad_3)
                            .addComponent(Btn_Unidad_2)
                            .addComponent(Btn_Unidad_1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Btn_Unidad_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Unidad_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Unidad_3)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Salir)
                    .addComponent(Btn_Integrantes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Unidad_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Unidad_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Unidad_1ActionPerformed

    private void Btn_Unidad_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Unidad_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Unidad_3ActionPerformed

    private void Btn_IntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IntegrantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_IntegrantesActionPerformed

    private void Btn_Unidad_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Unidad_3MouseClicked
        // TODO add your handling code here:
        Vent_Unidad_3 unidad_3=new Vent_Unidad_3();
        
        unidad_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_Unidad_3MouseClicked

    private void Btn_Unidad_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Unidad_2MouseClicked
        // TODO add your handling code here:
        Vent_Unidad_2 unidad_2=new Vent_Unidad_2();
        unidad_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_Unidad_2MouseClicked

    private void Btn_Unidad_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Unidad_1MouseClicked
        // TODO add your handling code here:
        Vent_Unidad_1 unidad_1=new Vent_Unidad_1();
        unidad_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_Unidad_1MouseClicked

    private void Btn_IntegrantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_IntegrantesMouseClicked
        // TODO add your handling code here:
        Vent_Integrantes integrantes=new Vent_Integrantes();
        integrantes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_IntegrantesMouseClicked

    private void Btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);//cierra
    }//GEN-LAST:event_Btn_SalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vent_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Integrantes;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Btn_Unidad_1;
    private javax.swing.JButton Btn_Unidad_2;
    private javax.swing.JButton Btn_Unidad_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
